#!/bin/bash
# 
#

apply() {
    sed -i --follow-symlinks "$1" "$2"
}

themedir=$(echo $0 | sed 's/\/apply-theme//')/themes

if [ "$#" = 0 ]; then
    echo "Please specify theme directory"
    exit 1
else
    if [ ! -d "$themedir/$1" ]; then
        echo "Directory does not exist"
        exit 2
    else
        for prgm in $(ls $themedir/$1); do
            echo "Applying $1 to $prgm"
            source $themedir/$1/$prgm/apply.sh
        done
    fi
fi
